spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/easycut?reWriteBatchedInserts=true  # 생성/수정 시, 쿼리 묶어서 보내도록 ?reWriteBatchedInserts=true 추가
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        jdbc:
          batch_size: 20 # ?reWriteBatchedInserts=true 때 20개씩 묶어서 보내도록
        # 배치 처리 효율을 높이기 위해 쿼리 순서 정렬
        order_inserts: true
        order_updates: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration # 스키마 저장 위치 - 관례
      - classpath:db/seed      # 데이터 저장 위치 - 관례

  sql:
    init:
      mode: always

logging:
  level:
    io.project.easycut.easy_cut: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  cors:
    allowed-origins: "http://localhost:3000, http://localhost:5173, http://localhost:8080"